#OPENAI_API_KEY="YOUR OPENAI API KEY"
#SF_USER='SF USER NAME'
#SF_PASSWORD='SF PASSWORD FOR ABOVE USER'
#SF_ACCOUNT='SF ACCOUNT IDENTIFIER'
#SF_WAREHOUSE='SF WAREHOUSE'
#SF_DATABASE = 'SF DATABASE'
#SF_SCHEMA = 'SF SCHEMA'
#SF_ROLE='ACCOUNTADMIN'


# app_secrets.py

OPENAI_API_KEY = "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"
SQL_SERVER = 'IN3269974W2'
SQL_DATABASE = 'GEN_AI'
ODBC_DRIVER = 'ODBC Driver 17 for SQL Server'
